package com.siva.demo.utils

object Constants {
    const val APP_NAME = "Demo"
    const val ROUTE_HOME = "home"
    const val ROUTE_FOOD = "food"
    const val ROUTE_GROCERY = "grocery"
    const val ROUTE_CART = "cart"
    const val ROUTE_PROFILE = "profile"
    const val NAV_HOME = "Home"
    const val NAV_FOOD = "Food"
    const val NAV_GROCERY = "Grocery"
    const val NAV_CART = "Cart"
    const val NAV_PROFILE = "Profile"
    const val RESTAURANT_GOURMET_KITCHEN = "The Gourmet Kitchen"
    const val RESTAURANT_URBAN_BURGER = "Urban Burger"
    const val RESTAURANT_SUSHI_ZEN = "Sushi Zen"
    const val RESTAURANT_GREEN_LEAF = "Green Leaf"
    const val RESTAURANT_SWEET_DREAMS = "Sweet Dreams"
    const val RESTAURANT_PIZZA_PARADISO = "Pizza Paradiso"
    const val RESTAURANT_BURGER_KING = "Burger King"
    const val RESTAURANT_WOK_ON_WHEELS = "Wok on Wheels"
    const val RESTAURANT_TACO_BELL = "Taco Bell"

    const val CUISINE_ITALIAN = "Italian"
    const val CUISINE_AMERICAN = "American"
    const val CUISINE_JAPANESE = "Japanese"
    const val CUISINE_SALADS = "Salads"
    const val CUISINE_BAKERY = "Bakery"
    const val CUISINE_PIZZA = "Pizza"
    const val CUISINE_BURGERS = "Burgers"
    const val CUISINE_CHINESE = "Chinese"
    const val CUISINE_MEXICAN = "Mexican"

    const val DELIVERY_25_30 = "25-30 min"
    const val DELIVERY_15_20 = "15-20 min"
    const val DELIVERY_35_40 = "35-40 min"
    const val DELIVERY_20_25 = "20-25 min"
    const val DELIVERY_30_35 = "30-35 min"

    const val CATEGORY_VEGETABLES = "Vegetables"
    const val CATEGORY_FRUITS = "Fruits"
    const val CATEGORY_DAIRY_EGGS = "Dairy & Eggs"
    const val CATEGORY_BAKERY = "Bakery"
    const val CATEGORY_SNACKS = "Snacks"
    const val CATEGORY_BEVERAGES = "Beverages"
    const val CATEGORY_MEAT = "Meat"
    const val CATEGORY_CLEANING = "Cleaning"

    const val USER_NAME = "Siva"
    const val USER_EMAIL = "sivademo@gmail.com"

    const val SECTION_TRENDING = "Trending Now"
    const val SECTION_POPULAR = "Popular Near You"
    const val SECTION_SEE_ALL = "See All"

    const val TITLE_FOOD = "Explore Food"
    const val TITLE_GROCERY = "Groceries"
    const val TITLE_CART = "Your Cart"
    const val TITLE_PROFILE = "Profile"

    const val EMPTY_CART_TITLE = "Your cart is feeling lonely"
    const val EMPTY_CART_SUBTITLE = "Explore our wide range of foods and groceries and add items to your cart."
    const val PROCEED_TO_PAY = "Proceed to Pay"
    const val BILL_SUMMARY = "Bill Summary"
    const val ITEM_TOTAL = "Item Total"
    const val DELIVERY_FEE = "Delivery Fee"
    const val TAXES = "Taxes"
    const val TO_PAY = "To Pay"

    const val OPTION_ORDERS = "Your Orders"
    const val OPTION_FAVORITES = "Favorite Restaurants"
    const val OPTION_ADDRESSES = "Saved Addresses"
    const val OPTION_PAYMENTS = "Payments"
    const val OPTION_SETTINGS = "Settings"
    const val OPTION_HELP = "Help & Support"
    const val OPTION_LOGOUT = "Logout"

    const val DESC_SEARCH = "Search"
    const val DESC_NOTIFICATIONS = "Notifications"
    const val DESC_FILTER = "Filter"
    const val DESC_PROFILE_PICTURE = "Profile Picture"
}
